### ISSUE TITLE
Encoding & Endpoints  errors

### ISSUE THREAD

**Issue by c-bertran** [c-bertran/express-autoindex#2]
Thank you @c-bertran for your effort put into fixing this. I really appreciate it and thank you. Error 500 has been fixed, but unfortunately, a few new errors have appeared now.

1. In the `express-autoindex@^1.3.0` version, the __character encoding__ for static files __has stopped working correctly__.
- Video: https://cdn.sefinek.net/static/22.07.2023/webstorm64_PgG06MUWq9OQ.mp4
- Polish (Programmers) and Russian keyboard: https://cdn.sefinek.net/static/22.07.2023/webstorm64_9Rko9ybH8WMr.mp4
> `test.txt file encoding: UTF-8 without BOM`
2. Endpoints like `/xxx/yyy/zzz/generated` __do not work with__ `express-autoindex`, even though they __are correctly served statically__.
- Video: https://cdn.sefinek.net/static/22.07.2023/webstorm64_gZF00ztFbIfT.mp4
- 400 Error: https://cdn.sefinek.net/static/22.07.2023/webstorm64_7QzWA7J4aFmg.mp4

Thank you also for adding the `customTemplate` option! There is no other npm module like yours, so I plan to use it anyway - even if it doesn't work perfectly 100%.

_Originally posted by @sefinek24 in https://github.com/c-bertran/express-autoindex/issues/1#issuecomment-1646323885_

**Comment by c-bertran** [comment]
I've just added the best possible management of file encoding. It's quite complex and it's possible in some rare cases for the encoding to be unsuitable, but frankly there's very little risk.

As for the endpoints, I've been working on them for a while, and I'm confident I'll find a solution.

**Comment by c-bertran** [comment]
Version 1.4.0 has just been released, and I've corrected the encoding bug in the received file, as well as the multipath bug.

Normally, things should be much better

**Comment by c-bertran** [comment]
To close the issue, I'd need to know whether the bugs observed have been corrected or not on your project.
Thanks in advance ^^

**Comment by sefinek** [comment]
It works! Thank you again, have a nice day or night!
See: https://blocklist.sefinek.net/json



![202](https://github.com/c-bertran/express-autoindex/assets/92880265/261ed072-8470-4161-8934-3e7c1b822f7d)
