### ISSUE TITLE
Asynchronously served static files

### ISSUE THREAD

**Issue by sefinek** [c-bertran/express-autoindex#3]
Unfortunately, a new error has appeared, this time again related to static files.

The error occurs because the `express-autoindex` module waits for the client to download the file, causing the entire server to hang. An example file download takes `50129.812 ms` - during this time, the server is unable to process other requests.

Video: https://cdn.sefinek.net/static/23.07.2023/explorer_WSW3JMRxU5zI.mp4
![WindowsTerminal_e7kmxOW0ABpp](https://github.com/c-bertran/express-autoindex/assets/92880265/7537b632-7637-4b9e-b328-fe301460c79c)

**Comment by sefinek** [comment]
https://github.com/sefinek24/Sefinek-Blocklist-Collection/commit/a3fcdc9d19ca522cb3276a148f61ff52676469b6

**Comment by c-bertran** [comment]
I'll end up believing that nothing works ^^
I'll look into it as soon as possible

**Comment by sefinek** [comment]
https://cdn.sefinek.net/static/23.07.2023/webstorm64_oak981mHXAez.mp4

**Comment by c-bertran** [comment]
Version 1.4.1 has just been released.
So files are now sent asynchronously. I've done quite a few tests with files of several tens of GB, and the server no longer blocks them.
I've also added the HTTP header Last-Modified to each file sent, which is still useful and consumes very few resources.

I've also found a Windows-related bug: folders with spaces were leading to 404 errors in the best of cases. And now it's even possible to point to an entire disk (with C:\, for example).

Don't hesitate to let me know how well it works @sefinek24

**Comment by sefinek** [comment]
It looks like everything is probably working @c-bertran! But I have a feeling that the code is displaying incorrect dates, or maybe I messed something up in the code.

Production: https://blocklist.sefinek.net/generated/127.0.0.1

![brave_GIvzdJ4dIuuK](https://github.com/c-bertran/express-autoindex/assets/92880265/757de93f-20c1-468d-8eb8-2143f1d4a602)

**Comment by sefinek** [comment]
After analyzing the headers, I confirm that `Last-Modified` does not display the correct value. The file's last modification date is included in the `Date` header.

**System date on my workspace:** 04:26, July 25, 2023
**System date on the blocklist.sefinek.net server:** Tue Jul 25 04:26:42 CEST 2023

![explorer_IrHl3SyIeNEz](https://github.com/c-bertran/express-autoindex/assets/92880265/23a568b7-0bdb-44ef-a1f3-c1043a46e1c3)

**Comment by c-bertran** [comment]
So, as always, it was the calamitous management of the Date javascript object that was to blame. So I decided to go ahead and parse the date provided by NodeJS by hand.

I had the same problem on my side.

Now the header is correct, as are the file and folder dates in UTC.
I've also added two new date format flags.

I hope that everything will now be working properly with version 1.4.2.

**Comment by sefinek** [comment]
I confirm, the dates are now displayed correctly.

**Comment by c-bertran** [comment]
Fine then, I'll add you to the list of contributors, it was nice of you to be so patient.
